<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	'The property filterSelector should be defined.' => 'Свойство filterSelector должно быть определено.',
	'The property updateSelector should be defined.' => 'Свойство updateSelector должно быть определено.',
	'Are you sure you want to delete this item?' => 'Ҳақиқатан хам ушбу маълумотни ўчиришни хохлайсизми?',
	'Delete' => 'Ўчириш',
	'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '{count} та элементдан {start}-дан {end}-гача.',
	'Either "name" or "value" must be specified for CDataColumn.' => 'Для CDataColumn необходимо указать "name" или "value".',
	'Home' => 'Бош саҳифа',
	'About' => 'Биз ҳақимизда',
	'Contact' => 'Алоқа',
	'Login' => 'Кириш',
	'Logout' => 'Чиқиш',
	'Copyright' => 'Нусха олиш ҳуқуқи',
	'Contact Us' => 'Биз билан боғланинг',
	'Fields with {require} are required'=> '{require} билан ажратилган майдонлар тўлдирилиши шарт',
	'No results found.' => 'Натижа йўқ.',
	'Not set' => 'Берилмаган',
	'Please specify the "attributes" property.' => 'Задайте свойство "attributes".',
	'Please specify the "data" property.' => 'Задайте свойство "data".',
	'Sort by: ' => 'Саралаш: ',
	'The "dataProvider" property cannot be empty.' => 'Свойство "dataProvider" не может быть пустым.',
	'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Атрибут должен быть указан в формате "Имя:Тип:Заголовок". "Тип" и "Заголовок" не обязательны.',
	'The button type "{type}" is not supported.' => 'Тип кнопки "{type}" не поддерживается.',
	'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Столбец должен быть указан в формате "Name:Type:Label". "Тип" и "Заголовок" не обязательны.',
	'The property "itemView" cannot be empty.' => 'Свойство "itemView" не может быть пустым.',
	'Total 1 result.|Total {count} results.' => 'Всего {count} результат.|Всего {count} результата.|{count} результатов.|{count} результата.',
	'Update' => 'Ўзгартириш',
	'View' => 'Кўриш',
	'{class} must specify "model" and "{attribute}" or "{name}" property values.' => 'В классе {class} должны быть заданы значения свойств "model" и "{attribute}", либо значение "{name}".',
	'All Rights Reserved' => 'Барча ҳуқуқлар ҳимояланган',
	'Verification Code'=>'Текширув коди',
	'Name'=>'Исми',
	'E-mail'=>'Электрон почта',
	'Subject'=>'Мавзу',
	'Body'=>'Матн',
	'Captcha'=>'Captcha',
	'Remember me next time'=>'Кейинги сафар ёдлаб қолиш',
	'Username'=>'Фойдаланувчи',
	'Password'=>'Парол',
	'Hint: You may login with {demo} or {admin}.' => 'Изоҳ: Сиз {demo} ёки {admin} билан киришингиз мумкин.',
	'Please fill out the following form with your login credentials' => 'Мархамат логин ва паролингизни киритинг',
	'Create'=>'Қўшиш',
	'Save'=>'Сақлаш',
	'My Web Application'=>'Менинг Web иловам',
	'Please enter the letters as they are shown in the image above.'=>'Мархамат, тасвирда кўрсатилган ҳарфларни юқоридаги майдонга киритинг.',
	'Letters are not case-sensitive.'=>'Ҳарфлар катта-кичиклиги фарқланмайди.',
	'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'=>'Агар Сизда бизнес сўровингиз ёки бирор саволингиз бўлса қуйидаги формани тўлдиринг ва бизга маълумот қолдиринг. Рахмат.',
	'Error'=>'Хатолик',
	'Welcome to {appname}!'=>'{appname}га хуш келибсиз!',
	'Congratulations! You have successfully created your Yii application.'=>'Табриклайман! Сиз ўзингизнинг Yii-иловангизни мувафақиятли яратдингиз.',
	'You may change the content of this page by modifying the following two files'=>'Сиз бу саҳифангиз таркибини қуйидаги файлларни ўзгартириш орқали ўзгартиришингиз мумкин',
	'View file: {file}'=>'Кўриш файли: {file}',
	'Layout file: {file}'=>'Жойлашув файли: {file}',
	'For more details on how to further develop this application, please read the {documentation}.'=>'Ушбу иловани қандай ривожлантириш мумкинлиги ҳақида қўшимча маълумотларни билмоқчи бўлсангиз, мархамат {documentation}ни ўқинг.',
	'Feel free to ask in the {forum}, should you have any questions.'=>'Бирор саволингиз бўлса, {forum}дан бепул маслахат олишингиз мумкин.',
	'documentation'=>'йўриқнома',
	'forum'=>'форум',
	'This is a "static" page. You may change the content of this page by updating the file {file}.'=>'Бу ўзгармас саҳифа. Бу саҳифанинг таркибига ўзгартириш киритиш учун {file} файлини янгилашингиз мумкин.',
	'List {label}'=>'{label}лар рўйхати',
	'Create {label}'=>'Янги {label}ни рўйхатга олиш',
	'Manage {label}'=>'{label}ни бошқариш',
	'Update {label}'=>'{label} маълумотларини ўзгартириш',
	'Delete {label}'=>'{label} маълумотларини ўчириш',
	'Advanced Search'=>'Қўшимча қидириш параметрлари',
	'View {label}'=>'{label}ни кўриш',
	'Update {table} "{record}" (id={id})'=>'{table}нинг "{record}" (id={id}) ёзувини ўзгартириш',
	'Table'=>'Жадвал',
	'Operations'=>'Амаллар',
	'Mobile'=>'Мобил талқин',
	'Full version'=>'Тўла талқин',
	''=>'',
	''=>'',
);
