<?php
/**
 * Locale data for 'uz'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '5912',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'UZS' => 'сўм',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'январ',
      2 => 'феврал',
      3 => 'март',
      4 => 'апрел',
      5 => 'май',
      6 => 'июн',
      7 => 'июл',
      8 => 'август',
      9 => 'сентябр',
      10 => 'октябр',
      11 => 'ноябр',
      12 => 'декабр',
    ),
    'abbreviated' => 
    array (
      1 => 'Янв',
      2 => 'Фев',
      3 => 'Мар',
      4 => 'Апр',
      5 => 'Май',
      6 => 'Июн',
      7 => 'Июл',
      8 => 'Авг',
      9 => 'Сен',
      10 => 'Окт',
      11 => 'Ноя',
      12 => 'Дек',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Я',
      2 => 'Ф',
      3 => 'М',
      4 => 'А',
      5 => 'М',
      6 => 'И',
      7 => 'И',
      8 => 'А',
      9 => 'С',
      10 => 'О',
      11 => 'Н',
      12 => 'Д',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'якшанба',
      1 => 'душанба',
      2 => 'сешанба',
      3 => 'чоршанба',
      4 => 'пайшанба',
      5 => 'жума',
      6 => 'шанба',
    ),
    'abbreviated' => 
    array (
      0 => 'Як',
      1 => 'Ду',
      2 => 'Се',
      3 => 'Чр',
      4 => 'Па',
      5 => 'Жу',
      6 => 'Ша',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Я',
      1 => 'Д',
      2 => 'С',
      3 => 'Ч',
      4 => 'П',
      5 => 'Ж',
      6 => 'Ш',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'ar' => 'Арабча',
    'de' => 'Олмонча',
    'en' => 'Инглизча',
    'es' => 'Испанча',
    'fr' => 'Французча',
    'hi' => 'Ҳиндча',
    'it' => 'Италянча',
    'ja' => 'Японча',
    'pt' => 'Португалча',
    'ru' => 'Русча',
    'uz' => 'Ўзбек',
    'zh' => 'Хитойча',
  ),
  'scripts' => 
  array (
    'arab' => 'Араб',
    'cyrl' => 'Кирил',
    'latn' => 'Лотин',
  ),
  'territories' => 
  array (
    'af' => 'Афғонистон',
    'br' => 'Бразилия',
    'cn' => 'Хитой',
    'de' => 'Германия',
    'fr' => 'Франция',
    'gb' => 'Буюк Британия',
    'in' => 'Ҳиндистон',
    'it' => 'Италия',
    'jp' => 'Япония',
    'ru' => 'Россия',
    'us' => 'Қўшма Штатлар',
    'uz' => 'Ўзбекистон',
  ),
);
